### ISSUE TITLE
Editable Reproduction (Stationarity Issue)

### ISSUE THREAD

**Issue by firmai** [intive-DataScience/tbats#11]
What could be wrong with my data it works on pmdarima. But not with TBATS.

https://colab.research.google.com/drive/17Ye4byHITNn4DhEqup_mXfWLycgjNhuf

Even after making the data stationary (differencing) it still screamed the same error. 

Thanks in advance, and nice clean package! 

Regards!

**Comment by anqus** [comment]
I think I'm having the same issue as you. Do you get the following error? 

> ValueError: Could not successfully fit ARIMA to input data. It is likely your data is non-stationary. Please induce stationarity or try a different range of model order params. If your data is seasonal, check the period (m) of the data.

My notebook was working when I last ran it (maybe 6 weeks ago). I've tried dropping back to TBATS 1.0.8, (1.0.9 was released 8/01/2020) but no success.

**Comment by firmai** [comment]
Same issue, not sure what could be causing this. Good to know it's not isolated.

**Comment by cotterpl** [comment]
I will have a look into this soon. In the mean-time try using it with use_arma_errors=False

**Comment by lukedyer-peak** [comment]
This seems to be related to the statsmodel `0.11.0` update.  I went back to `0.10.2` and didn't get this bug anymore.

**Comment by cotterpl** [comment]
I have reviewed the issue. It lies inside pmdarima package that fails to work properly with statsmodel that @lukedyer-peak mentions. It works properly with 0.10.2. I am closing this as non TBATS related.
