### ISSUE TITLE
{ValueError}Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by mzietlow** [intive-DataScience/tbats#22]
I am currently playing around with the Numenta Anomaly Benchmark dataset and just ran into a dataframe that leads to _inf_ values for a tbats2 model (using atspy lingo).

I have tracked the issue down to the transformation.BoxCox.inv_boxcox function, in which a already high value gets exponentialized and thus flips _inf_. 

Beyond that however, I was unable to pinpoint the issue.

To replicate
a.) create a new csv file (example.csv) with contents from [my pastebin](https://pastebin.com/jb19eeKn)
b.) run respective python interpreter
c.)
```
from tbats import TBATS
data = pd.read_csv("./example.csv")
TBATS(seasonal_periods=[2, 5], use_arma_errors=False, use_box_cox=True).fit(data["Target"])
```

**Comment by cotterpl** [comment]
BoxCox transformation doesn't always work well. If you have values very close to zero or negative it may fail in such a way. Please rurn boxcox off using use_box_cox=False

**Comment by mzietlow** [comment]
Okay, thank you!
