### ISSUE TITLE
Refit TBATS on new data

### ISSUE THREAD

**Issue by gustavz** [intive-DataScience/tbats#31]
Is there an efficient way of refitting TBATS when new data is available to an already fitted model?

So e.g. are there some parameters in the fitted model that can be reused when re-fitting it on data that extends the fitted data by some new data? Or is it necessary to make a complete fit from scratch?

So for example if i fitted the model on t1-t10 and now i have t1-t15 available, what would be the most efficient way to refit the model?

**Comment by cotterpl** [comment]
Please see: https://github.com/intive-DataScience/tbats/blob/master/examples/re_fit_model.py . If you want new model parameters you need to do full fit.
