### ISSUE TITLE
Question: box_cox_bounds limits

### ISSUE THREAD

**Issue by gustavz** [intive-DataScience/tbats#32]
Are there any upper or lower limits to the `box_cox_bounds` argument?
If not implementation wise then maybe from a logical perspective...
Thanks!

I know Issues shouldn't be used for questions but i couldn't find another appropriate place (please link if available)

**Comment by cotterpl** [comment]
The default is between [0,1]. You can try higher or lower values but I doubt those would be useful on actual historical data.
