### ISSUE TITLE
Serious dependency issues with this library, not sure what to do

### ISSUE THREAD

**Issue by srivas53** [intive-DataScience/tbats#5]

**Comment by cotterpl** [comment]
It would be great to have some description. What errors are you seeing?

**Comment by srivas53** [comment]
Thanks for getting back to me! Yes, the error is:

AttributeError: type object 'pmdarima.arima._arima.array' has no attribute '__reduce_cython__'
I figured that it may be because of incompatible Cython or pmdarima versions, I checked the stable_reqs.txt, and upgraded/downgraded the libraries, and yet I cannot seem to get rid of this error. Any help will be appreciated

**Comment by srivas53** [comment]
@cotterpl Any suggestions will be appreciated, as I am currently doing a project with a hard deadline, and TBATS can be really helpful

**Comment by cotterpl** [comment]
It looks to be an internal issue with pmdarima and cython packages. This comment may be helpful: https://github.com/cython/cython/issues/1953#issuecomment-398128940 . I am unable to solve this for you as it is an low level issue not directly related to TBATS. I would try upgrading pmdarima to latest version. You may also try to setup a new environment from scratch.

**Comment by cotterpl** [comment]
Try also upgrading these numpy, scipy, scikit-learn, pandas, statsmodels

**Comment by cotterpl** [comment]
Closing as this looks to be an issue in dependent packages configurations
