### ISSUE TITLE
Value error issue

### ISSUE THREAD

**Issue by ValeMonLop** [intive-DataScience/tbats#9]
Hi! I was trying to import the package, and I got the following:

ValueError                                Traceback (most recent call last)
<ipython-input-12-e296182eaa5e> in <module>()
----> 1 from tbats import TBATS

~/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/tbats/__init__.py in <module>()
----> 1 import tbats.abstract as abstract
      2 import tbats.bats as bats
      3 import tbats.tbats as tbats
      4 from .bats import BATS
      5 from .tbats import TBATS

~/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/tbats/abstract/__init__.py in <module>()
      9 from .ParamsOptimizer import ParamsOptimizer
     10 from .SeedFinder import SeedFinder
---> 11 from .Case import Case
     12 from .Estimator import Estimator
     13 from .ContextInterface import ContextInterface

~/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/tbats/abstract/Case.py in <module>()
----> 1 from pmdarima.arima import auto_arima
      2 
      3 
      4 class Case(object):
      5     """Provides means to choose best model for provided components setup

~/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/pmdarima/__init__.py in <module>()
     27 
     28     # Stuff we want at top-level
---> 29     from .arima import auto_arima, ARIMA, AutoARIMA
     30     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf
     31 

~/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/pmdarima/arima/__init__.py in <module>()
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      4 
----> 5 from .approx import *
      6 from .arima import *
      7 from .auto import *

~/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/pmdarima/arima/approx.py in <module>()
     17 # and since the platform might name the .so file something funky (like
     18 # _arima.cpython-35m-darwin.so), import this absolutely and not relatively.
---> 19 from pmdarima.arima._arima import C_Approx
     20 
     21 __all__ = [

__init__.pxd in init pmdarima.arima._arima()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Can you help me please?

**Comment by cotterpl** [comment]
Given the stack trace it seems it is an numpy and arima package dependencies issue. It is not a TBATS issue. Try setting up environment properly. It seems numpy is not installed properly.
